#!/usr/bin/env bash
STOW_FOLDERS="general,git,tmux,nvim,zsh,personal"
DOTFILES=$HOME/.dotfiles

pushd $DOTFILES > /dev/null

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd > /dev/null
